# The setup for Selenium Grid is taken from
# https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#docker-compose

services:
  chrome:
    image: selenium/node-chrome:4.28.1-20250202
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.28.1-20250202
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.28.1-20250202
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  selenium-tests-chrome:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
    command: [ "uv", "run", "pytest", "--headless", "--selenium_grid", "--browser", "chrome" ]

  selenium-tests-firefox:
    build: .
    depends_on:
      - selenium-hub
      - firefox
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
    command: [ "uv", "run", "pytest", "--headless", "--selenium_grid", "--browser", "firefox" ]
